Qos setting
upowerrobotics/ros2_fabric pull request #28
Opened 2023-09-05 23:03 UTC by ihkao

Close #17

2023-09-07 18:44 UTC, JWhitleyWork requested changes

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/config/example.yaml
> +            QoS_policy: reliable
Even though QoS is an acronym, I would prefer to keep these lower-case to match the other field names.

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/docs/YAML_API.md
> +  when the **history_policy** is set to **RMW_QOS_POLICY_HISTORY_KEEP_LAST**.
Since we are controlling all of the other QoS settings through the node, we probably don't need to mention the `history_policy` (especially since it can't currently be changed through the YAML config).

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/fabric_nodes/config2node.py
> +                            f"must be >= 0")
The description of `qos_policy` says that setting this to 0 also sets the `history_policy` to `keep_all` so 0 seems to be a valid value.

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/docs/YAML_API.md
> +  The policy can either be **reliable** or **best_effort**. (Default: reliable)
I would suggest we not apply the `qos` values to subscribers, but only to publishers and we have the subscribers query the topic and mirror what the publisher is doing. I've seen a code example of how to do this but I'll have to find it again.

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/src/dummy_node.cpp
> +  }
Why was this moved?

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/src/dummy_node.cpp
> +    0) ? rclcpp::QoS{pub.qos_setting.depth} : rclcpp::QoS{rclcpp::KeepAll()};
0 seems to be valid so I think this is incorrect an dwill automatically set the `KeepAll` if the value is 0.

2023-09-07 18:44 UTC, JWhitleyWork commented on fabric_nodes/test_config/error_sub_connection_qty.test.yaml
> +            QoS_policy: reliable
It probably isn't necessary for us to set `qos_depth` for every topic. In fact, we want some without this setting just to verify that it defaults correctly.

2023-09-07 19:46 UTC, ihkao commented on fabric_nodes/config/example.yaml
> +            QoS_policy: reliable
Adjust in [e085399](https://github.com/upowerrobotics/ros2_fabric/pull/28/commits/e0853992dc3344a6c6b8e354fc75c4afb571ca77)

2023-09-07 20:45 UTC, ihkao commented on fabric_nodes/docs/YAML_API.md
> +  The policy can either be **reliable** or **best_effort**. (Default: reliable)
I think is `get_publishers_info_by_topic`.  
Refer to [node_graph_interface.hpp](https://docs.ros2.org/foxy/api/rclcpp/node__graph__interface_8hpp_source.html)  
Will work on it.

2023-09-07 20:48 UTC, ihkao commented on fabric_nodes/fabric_nodes/config2node.py
> +                            f"must be >= 0")
Indeed, so the I made the Judgmental  
`if qos_depth is not None and qos_depth < 0:`

2023-09-07 21:16 UTC, ihkao commented on fabric_nodes/docs/YAML_API.md
> +  The policy can either be **reliable** or **best_effort**. (Default: reliable)
Adjust in [386ede4](https://github.com/upowerrobotics/ros2_fabric/pull/28/commits/386ede41c821590ae9ae95ff396edde3170a9598)

2023-09-07 21:22 UTC, ihkao commented on fabric_nodes/src/dummy_node.cpp
> +  }
move it back in [431f170](https://github.com/upowerrobotics/ros2_fabric/pull/28/commits/431f1705dce9a55cad202ed9119f77c107a0e2e7)

2023-09-07 21:25 UTC, ihkao commented on fabric_nodes/test_config/error_sub_connection_qty.test.yaml
> +            QoS_policy: reliable
Adjust in [19474c7](https://github.com/upowerrobotics/ros2_fabric/pull/28/commits/19474c787c27b60209dcff75f93694322e018d69)

2023-09-07 21:28 UTC, ihkao commented on fabric_nodes/src/dummy_node.cpp
> +    0) ? rclcpp::QoS{pub.qos_setting.depth} : rclcpp::QoS{rclcpp::KeepAll()};
We have made the `config2node.py` check the validation of the depth param. Which only when this param is >=0 will trigger `dummy_node.cpp`.
The data structure of the pub.qos_setting.depth is size_t, which there will be no value under 0. Therefore, we only need to check if the value is 0.

2023-09-07 21:34 UTC, ihkao commented on fabric_nodes/docs/YAML_API.md
> +  when the **history_policy** is set to **RMW_QOS_POLICY_HISTORY_KEEP_LAST**.
Adjust in [e6b16be](https://github.com/upowerrobotics/ros2_fabric/pull/28/commits/e6b16be0078b8efdb008b24d56317b793fed6f1b)

2023-09-08 16:33 UTC, ihkao commented on fabric_nodes/docs/YAML_API.md
> +  The policy can either be **reliable** or **best_effort**. (Default: reliable)
Instead of using rclcpp::sleep_for to wait the publisher to be created. I use while loop to look for it.  
check in [359a2f4](https://github.com/upowerrobotics/ros2_fabric/pull/28/commits/359a2f4355d65645136527f8400e8196176a64fb)

2023-09-08 17:19 UTC, JWhitleyWork commented on fabric_nodes/src/dummy_node.cpp
> +  }
You should include at least *some* form of sleep here. Otherwise this will use 100% of the CPU core that it's on to run this loop as fast as possible. 100ms is pretty common.

2023-09-08 17:42 UTC, JWhitleyWork approved these changes

2023-09-08 17:42 UTC, merged