combine into one csv
upowerrobotics/ros2_fabric pull request #29
Opened 2023-09-06 20:09 UTC by LawrenceXu13467

All log info should be in one single csv now

2023-09-06 23:53 UTC, ihkao requested changes

2023-09-06 23:53 UTC, ihkao commented on fabric_nodes/fabric_nodes/get_log.py
> +        topic_bw = str(re.search(r'(?<=Bandwidth:\s)\d*', log).group()) or None
There will be multipule units for the bandwidth:  
"B", "KB", "MB", "GB"

2023-09-07 20:22 UTC, LawrenceXu13467 commented on fabric_nodes/fabric_nodes/get_log.py
> +        topic_bw = str(re.search(r'(?<=Bandwidth:\s)\d*', log).group()) or None
Fixed in https://github.com/upowerrobotics/ros2_fabric/pull/29/commits/d4d57753454b4c0473961b7cde952a007a92441e.

2023-09-07 21:50 UTC, ihkao commented
Try get the line in this commit [c99626f](https://github.com/upowerrobotics/ros2_fabric/pull/29/commits/c99626fdc03a3ea7748c7e561348d6819576288c)

2023-09-08 16:45 UTC, merged